# Generated by Django 3.0.7 on 2020-06-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_auto_20200618_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(verbose_name='update timestamp'),
        ),
    ]
