# Generated by Django 3.0.7 on 2020-06-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0007_auto_20200618_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
