# Generated by Django 3.0.7 on 2020-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_remove_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
