# Generated by Django 3.0.7 on 2020-06-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_blog_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
    ]
