# Generated by Django 3.0.7 on 2020-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0011_remove_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='creation timestamp'),
        ),
    ]
