# Generated by Django 3.0.7 on 2020-06-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0014_remove_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
